#!/usr/bin/env python
"""Build a categorised sanity-check issues markdown from a sanity_check.py JSONL.

Usage:
    python build_issues_md.py [--jsonl PATH] [--out PATH]

Defaults read PYCMOR_SANITY_JSONL / PYCMOR_SANITY_OUT_MD env vars or
fall back to /tmp/sanity_check_results.jsonl and ../../issues_sanity.md.
"""
import argparse
import json
import os
import re
from collections import Counter, defaultdict
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument("--jsonl",
               default=os.environ.get("PYCMOR_SANITY_JSONL",
                                      "/tmp/sanity_check_results.jsonl"))
p.add_argument("--out",
               default=os.environ.get(
                   "PYCMOR_SANITY_OUT_MD",
                   str(Path(__file__).resolve().parents[2] / "issues_sanity.md")))
ARGS = p.parse_args()
JSONL = Path(ARGS.jsonl)
OUT = Path(ARGS.out)

records = []
with open(JSONL) as fh:
    for line in fh:
        line = line.strip()
        if not line: continue
        try:
            records.append(json.loads(line, parse_constant=lambda x: float("nan")))
        except Exception:
            pass

# Status totals
total = len(records)
sc = Counter(r.get("status","?") for r in records)

# By var collapse, FAIL only
var_status = defaultdict(lambda: {"counts": Counter(), "examples": [], "all_files": []})
for r in records:
    v = r.get("var","?")
    var_status[v]["counts"][r.get("status","?")] += 1
    var_status[v]["all_files"].append(r)
    if r.get("status") == "FAIL" and len(var_status[v]["examples"]) < 1:
        var_status[v]["examples"].append(r)

def severity(notes):
    text = "; ".join(notes).lower()
    if "non-finite" in text: return "DATA_INTEGRITY"
    if "wrong sign" in text: return "SIGN_FLIP"
    m = re.search(r"off by ([\d.eE+-]+)x", text)
    if m:
        try:
            f = float(m.group(1))
            if f > 1e3: return "UNIT_MISMATCH"
        except Exception: pass
    if "above expected_max 0" in text or "below expected_min 0" in text:
        return "PICONTROL_NONZERO"
    if "slightly" in text:
        return "BOUNDS_TIGHT_MINOR"
    return "BOUNDS_OR_PEAK"

# Special-case: detect physical-impossibility sign bugs (negative mass, neg thickness)
SIGN_BUGS = {"masscello": "Mass per area must be non-negative.",
             "thkcello": "Cell thickness must be positive."}

fail_vars = [(v,x) for v,x in var_status.items() if x["counts"].get("FAIL",0) > 0]
fail_vars.sort(key=lambda v: (-v[1]["counts"].get("FAIL",0), v[0]))

by_sev = defaultdict(list)
for v, x in fail_vars:
    if v in SIGN_BUGS:
        sev = "PHYS_IMPOSSIBLE"
    else:
        ex = x["examples"][0]
        sev = severity(ex.get("notes",[]))
    by_sev[sev].append((v, x))

def fmt_actual(ex):
    return (f"min `{ex.get('min', '?'):.3g}` | mean `{ex.get('mean', '?'):.3g}` | "
            f"max `{ex.get('max', '?'):.3g}`")

def fmt_expected(ex):
    return (f"min `{ex.get('expected_min', '?')}` | mean `{ex.get('expected_mean', '?')}` | "
            f"max `{ex.get('expected_max', '?')}`")

def affected_files_list(x, status="FAIL", limit=None):
    fs = [r for r in x["all_files"] if r.get("status") == status]
    out = []
    for r in fs[:limit] if limit else fs:
        out.append(f"`{r.get('dir','?')}/{Path(r.get('file','')).name}`")
    return out

# WARN-only
warn_only = sorted({v for v,x in var_status.items()
                   if x["counts"].get("WARN",0) > 0 and x["counts"].get("FAIL",0) == 0})

# Top-fail dirs
by_dir = defaultdict(Counter)
for r in records:
    by_dir[r.get("dir","?")][r.get("status","?")] += 1

# --------- Build markdown ---------
lines = []
A = lines.append

A("# Sanity-check findings — Test_16n_y1587 (HR piControl, year 1587)")
A("")
A(f"Generated by walking `{total}` of 695 .nc files in")
A(f"`/scratch/a/a270092/pycmor_hr/Test_16n_y1587/cmorized/{{17 live dirs}}` and")
A("comparing global (nan-skipping, fill-aware) min / mean / max against literature")
A("bounds in [doc/sanity_check_ranges.md](doc/sanity_check_ranges.md). Walker:")
A("`/tmp/sanity_check.py` (chunked netCDF4 reads, per-file subprocess + timeout,")
A("streaming JSONL output, resume-on-restart).")
A("")
A("**Scope:** items below are flagged for **another AI to investigate and fix**.")
A("Each entry says exactly which files to look at, what the symptom is, and the")
A("most likely root cause.")
A("")

# Summary table
A("## Summary")
A("")
A(f"- **Files processed:** {total} / 695")
A(f"- **PASS:** {sc.get('PASS',0)} ({100*sc.get('PASS',0)/max(total,1):.1f}%)")
A(f"- **WARN:** {sc.get('WARN',0)} ({100*sc.get('WARN',0)/max(total,1):.1f}%)  — bound minor overshoot or far-from-mean; see Category C/D")
A(f"- **FAIL:** {sc.get('FAIL',0)} ({100*sc.get('FAIL',0)/max(total,1):.1f}%)  — flagged below")
A(f"- **ERROR:** {sc.get('ERROR',0)} — read failures (timeouts on giant 4D files; retried separately)")
A("")
A("### Per-directory")
A("")
A("| Directory | PASS | WARN | FAIL | ERROR |")
A("|---|---:|---:|---:|---:|")
for d in sorted(by_dir):
    c = by_dir[d]
    A(f"| {d} | {c.get('PASS',0)} | {c.get('WARN',0)} | {c.get('FAIL',0)} | {c.get('ERROR',0)} |")
A("")

# ---- Categories ----

SEV_TITLES = {
    "DATA_INTEGRITY": "Category A1 — Data integrity (file is all-fill / NaN)",
    "PHYS_IMPOSSIBLE": "Category A2 — Physical impossibility (negative mass, negative thickness)",
    "UNIT_MISMATCH": "Category A3 — Unit mismatch (off by orders of magnitude)",
    "SIGN_FLIP": "Category A4 — Sign / baseline flipped",
    "PICONTROL_NONZERO": "Category B — piControl forcing residuals (model behaviour, not pycmor)",
    "BOUNDS_OR_PEAK": "Category C — Grid-cell peak overshoots (bounds in ranges.md too tight)",
    "BOUNDS_TIGHT_MINOR": "Category D — Slight overshoots (cosmetic; bounds.md needs widening)",
}
SEV_DESC = {
    "DATA_INTEGRITY": ("These files contain no finite values. Pipeline emitted only "
                       "fill values. **Real bug** — must be fixed before publication."),
    "PHYS_IMPOSSIBLE": ("Variable has values that cannot occur physically. "
                        "**Real bug** in the producing rule's compute step."),
    "UNIT_MISMATCH": ("Output is off by ~10³ or more vs the CMIP-declared units. "
                      "Likely a missing unit-conversion step. **Real bug**."),
    "SIGN_FLIP": ("Values systematically have the wrong sign or anomaly baseline. "
                  "**Real bug** — the rule emits the wrong physical quantity."),
    "PICONTROL_NONZERO": ("These should be ~0 in CMIP-style piControl (no anthropogenic "
                          "forcing) but the model emits non-zero values. Either the LU "
                          "forcing dataset isn't being honoured, or this is intentional "
                          "internal model behaviour to document. **Investigate** rather "
                          "than fix in pycmor."),
    "BOUNDS_OR_PEAK": ("Grid-cell extrema overshoot the bound, but global means are "
                       "reasonable. **Bounds were set for global mean** at LR resolution; "
                       "HR grid cells legitimately have higher peaks. Loosen bounds in "
                       "`doc/sanity_check_ranges.md` rather than touching the model."),
    "BOUNDS_TIGHT_MINOR": ("Output marginally exceeds the bound. **Loosen bounds.**"),
}

# Hand-tuned action notes for known cases
ACTIONS = {
    "sfdsi": "Inspect `lrcs_seaice` rule: source FESOM `salt_in_ice` field may be missing/all-fill, or a divide-by-zero in the compute step. Check the pipeline in `awi-esm3-veg-hr-variables/lrcs_seaice/cmip7_awiesm3-veg-hr_lrcs_seaice.yaml`.",
    "sicompstren": "Check FESOM `pice` / `pstar` source field. Pipeline path: `awi-esm3-veg-hr-variables/lrcs_seaice/`.",
    "ua": "The 6hr files for `158701010900-...` (full year) and `158801010300` are all-fill. Check why ua-6hr was scheduled to write but no data flowed in. Look at the XIOS file_def for the 6hr ua plev3 stream and the compute step in `cap7_atm` or `core_atm`.",
    "vsfcorr": "Source variable in FESOM is likely missing/zero. Check `lrcs_ocean` rule for vsfcorr.",
    "masscello": "An fx file with negative mass per area is impossible. Likely the compute step subtracts something wrongly. Look at the masscello rule in `awi-esm3-veg-hr-variables/core_ocean/cmip7_awiesm3-veg-hr_ocean.yaml`.",
    "thkcello": "An fx file with negative cell thickness is impossible. Same rule yaml as masscello. The mean (1.23 m) suggests the column is being computed as differences without abs().",
    "siarea": "Output is in raw m² but CMIP7 declares units `1e6 km2`. Add `source_units: m2` to the rule, or insert a ÷1e12 conversion step. File: `awi-esm3-veg-hr-variables/lrcs_seaice/cmip7_awiesm3-veg-hr_lrcs_seaice.yaml`.",
    "siextent": "Same issue as siarea. Same yaml.",
    "sweLut": "JSBACH outputs SWE in `kg m-2`, CMIP7 expects `m`. Add `source_units: kg m-2` so pint runs ÷1000. File: `awi-esm3-veg-hr-variables/veg_land/cmip7_awiesm3-veg-hr_land.yaml`.",
    "pso": "Variable saved as anomaly instead of absolute pressure. Either the compute step uses ssh-derived ρ·g·η without adding p_atm, or the source field is `dssh` not absolute pressure. File: `awi-esm3-veg-hr-variables/lrcs_ocean/cmip7_awiesm3-veg-hr_lrcs_ocean.yaml`.",
}

SEV_ORDER = ["DATA_INTEGRITY", "PHYS_IMPOSSIBLE", "UNIT_MISMATCH", "SIGN_FLIP",
             "PICONTROL_NONZERO", "BOUNDS_OR_PEAK", "BOUNDS_TIGHT_MINOR"]

for sev in SEV_ORDER:
    grp = by_sev.get(sev, [])
    if not grp: continue
    A(f"## {SEV_TITLES[sev]}")
    A("")
    A(SEV_DESC[sev])
    A("")
    for v, x in grp:
        ex = x["examples"][0]
        A(f"### `{v}`")
        A("")
        c = x["counts"]
        cs = ", ".join(f"{s}={c[s]}" for s in c if c[s])
        A(f"- **Status:** {cs}")
        A(f"- **File units:** `{ex.get('units_in_file','?')}` · "
          f"**Table units:** `{ex.get('units','?')}` · "
          f"**Realm:** {ex.get('realm','?')}")
        if ex.get("min") is not None:
            try:
                A(f"- **Actual:** {fmt_actual(ex)}")
            except Exception:
                pass
        A(f"- **Expected:** {fmt_expected(ex)}")
        notes = "; ".join(ex.get("notes",[]))
        if notes:
            A(f"- **Symptom:** {notes}")
        if v in SIGN_BUGS:
            A(f"- **Why this is a bug:** {SIGN_BUGS[v]}")
        if v in ACTIONS:
            A(f"- **Action:** {ACTIONS[v]}")
        # Affected files
        affected = affected_files_list(x, status="FAIL")
        if affected:
            A("- **Affected file(s):**")
            for fp in affected[:6]:
                A(f"  - {fp}")
            if len(affected) > 6:
                A(f"  - … +{len(affected)-6} more")
        A("")

# WARN-only
A("---")
A("")
A("## Variables with WARN only (no FAIL)")
A("")
A(f"{len(warn_only)} variables warn (small overshoots or far-from-mean) but no FAIL. "
  "Most likely bounds-too-tight; review and loosen `doc/sanity_check_ranges.md` as needed.")
A("")
A(", ".join(f"`{v}`" for v in warn_only))
A("")

# Errors
errs = [r for r in records if r.get("status") == "ERROR"]
if errs:
    A("---")
    A("")
    A(f"## ERROR records ({len(errs)})")
    A("")
    A("Worker subprocess failed (typically timeout on giant 4D files). Re-run with")
    A("higher per-file timeout and/or `BLOSC_NTHREADS=8`.")
    A("")
    for r in errs:
        A(f"- `{r.get('dir','?')}/{Path(r.get('file','')).name}` — "
          f"{'; '.join(r.get('notes',[]))}")
    A("")

# Performance
A("---")
A("")
A("## Performance notes (slowest 10 files)")
A("")
slow = sorted([r for r in records if r.get("elapsed_s") is not None],
              key=lambda r: r.get("elapsed_s") or 0, reverse=True)
A("| Elapsed (s) | Dir | File |")
A("|---:|---|---|")
for r in slow[:10]:
    A(f"| {r.get('elapsed_s',0):.1f} | {r.get('dir','?')} | "
      f"`{Path(r['file']).name[:80]}` |")
A("")
A("Slow reads are dominated by blosc_zstd decompression of large 4D fields. "
  "The walker sets `BLOSC_NTHREADS=4` by default; increase for faster retries.")
A("")

OUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {OUT} ({sum(len(L) for L in lines)} bytes, {len(lines)} lines)")
