general:
  name: "awiesm3-cmip7-minimal"
  cmor_version: "CMIP7"
  mip: "CMIP"
  CMIP7_DReq_metadata: "/home/a/a270092/.cache/pycmor/cmip7_metadata/v1.2.2.2/metadata.json"

pycmor:
  warn_on_no_rule: False
  dask_cluster: "slurm"
  dask_cluster_scaling_mode: "adapt"
  dask_cluster_scaling_minimum_jobs: 1
  dask_cluster_scaling_maximum_jobs: 16

jobqueue:
  slurm:
    name: pycmor-worker
    queue: compute
    account: bb1469
    cores: 16
    memory: 256GB
    walltime: '00:30:00'

# Custom pipelines
pipelines:
  - name: ocean_vertical_integration_pipeline
    steps:
      - pycmor.core.gather_inputs.load_mfdataset
      - pycmor.std_lib.generic.get_variable
      - script:///work/ab0246/a270092/software/pycmor/examples/custom_steps.py:vertical_integrate
      - pycmor.std_lib.add_vertical_bounds
      - pycmor.std_lib.timeaverage.timeavg
      - pycmor.std_lib.units.handle_unit_conversion
      - pycmor.std_lib.attributes.set_global
      - pycmor.std_lib.attributes.set_variable
      - pycmor.std_lib.attributes.set_coordinates
      - pycmor.std_lib.dimensions.map_dimensions
      - pycmor.core.caching.manual_checkpoint
      - pycmor.std_lib.generic.trigger_compute
      - pycmor.std_lib.generic.show_data
      - pycmor.std_lib.files.save_dataset

# Common attributes inherited by all rules
inherit:
  source_id: AWI-ESM-3
  institution_id: AWI
  experiment_id: picontrol
  variant_label: r1i1p1f1
  grid_label: gn
  mesh_path: /work/ab0246/a270092/input/fesom2/dars2
  grid_file: /work/ab0246/a270092/input/fesom2/dars2/griddes.nc
  grid: "FESOM 2.6 unstructured grid DARS (3146761 surface nodes)"
  nominal_resolution: "10 km"
  institution: "Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Bremerhaven, Germany"
  output_directory: ./cmorized_output/awiesm3

rules:
  # Ocean surface temperature
  - name: tos
    inputs:
      - path: /work/bb1469/a270089/runtime/awiesm3-v3.4.1/AWI-ESM3-VEG-HR-CMIP7-Spinup_cont2/outdata/fesom
        pattern: sst.fesom.1350.nc
    compound_name: ocean.tos.tavg-u-hxy-sea.mon.GLB
    model_variable: sst

  # Depth-integrated absolute salinity (computed from 3D field)
  - name: absscint
    inputs:
      - path: /work/bb1469/a270089/runtime/awiesm3-v3.4.1/AWI-ESM3-VEG-HR-CMIP7-Spinup_cont2/outdata/fesom
        pattern: salt.fesom.1350.nc
    compound_name: ocean.absscint.tavg-op4-hxy-sea.mon.GLB
    model_variable: salt
    integration_attrs:
      long_name: "Integral wrt depth of seawater absolute salinity expressed as salt mass content"
      standard_name: "integral_wrt_depth_of_sea_water_absolute_salinity_expressed_as_salt_mass_content"
      units: "kg m-2"
    pipelines:
      - ocean_vertical_integration_pipeline
