"""
Set time bounds for datasets based on time method and approximate interval.

Time bounds represent the start and end of the time interval associated with
each time point. For climate data, these are required for CMIP compliance.

The main function is :func:`time_bounds` which creates appropriate bounds
based on the time method (mean, instantaneous, or climatology) and the
data's temporal frequency.
"""

import numpy as np
import xarray as xr

from ..core.logging import logger
from ..core.rule import Rule
from .dataset_helpers import get_time_label


def time_bounds(ds: xr.Dataset, rule: Rule) -> xr.Dataset:
    """
    Set time bounds for a variable based on time method and approx_interval.

    Time bounds are set according to the following logic:

    - For instantaneous time method: bounds equal the time values (delta = 0)
    - For mean time method: bounds span the averaging interval (delta > 0)
    - For climatology: no bounds are created
    - Uses approx_interval from rule to determine appropriate bounds

    Parameters
    ----------
    ds : xr.Dataset
        The input dataset.
    rule : Rule
        Rule object. Uses ``approx_interval`` (float, days) and
        ``time_method`` (str) attributes if present.

    Returns
    -------
    xr.Dataset
        The output dataset with time bounds information.

    Raises
    ------
    ValueError
        If the input is not a Dataset, has no time coordinate, or has
        insufficient time points for the requested bounds type.
    """
    dataset_name = ds.attrs.get("name", "unnamed_dataset")
    logger.info(f"[Time bounds] {dataset_name}")

    if not isinstance(ds, xr.Dataset):
        raise ValueError("The input is not a dataset.")

    time_label = get_time_label(ds)
    if time_label is None:
        raise ValueError("The dataset does not contain a valid time coordinate.")

    bounds_dim_label = "bnds"
    time_bounds_label = f"{time_label}_{bounds_dim_label}"

    approx_interval = getattr(rule, "approx_interval", None)
    time_method = getattr(rule, "time_method", None) or ds.attrs.get("time_method", "mean")

    logger.info(f"  time label: {time_label}, approx_interval: {approx_interval} days")
    logger.info(f"  time method: {time_method}")

    # Preserve existing bounds
    if time_bounds_label in ds.variables:
        logger.info(f"  using existing bounds: {time_bounds_label}")
        return ds

    if time_method not in ("mean", "instantaneous", "climatology"):
        logger.warning(f"  Unknown time method '{time_method}', defaulting to 'mean'")
        time_method = "mean"

    if time_method == "climatology":
        logger.info("  skipping bounds creation for climatology data")
        return ds

    time_var = ds[time_label]
    time_values = time_var.values

    if len(time_values) < 1:
        raise ValueError("Cannot create time bounds: no time points found")

    logger.info(f"  {len(time_values)} points from {time_values[0]} to {time_values[-1]}")

    if time_method == "instantaneous":
        bounds_data = np.column_stack([time_values, time_values])
    else:
        bounds_data = _create_mean_bounds(time_values, approx_interval)

    bounds = xr.DataArray(
        data=bounds_data,
        dims=(time_label, bounds_dim_label),
        coords={time_label: time_values, bounds_dim_label: [0, 1]},
        attrs={
            "long_name": f"time bounds for {time_label}",
            "comment": f"Generated by pycmor: {time_method} time bounds",
        },
    )

    ds = ds.assign_coords({time_bounds_label: bounds})

    if "bounds" not in time_var.attrs:
        ds[time_label].attrs["bounds"] = time_bounds_label

    logger.info(f"  set {time_bounds_label}{bounds.shape}, " f"range: {bounds.values[0][0]} to {bounds.values[-1][-1]}")
    return ds


def _create_mean_bounds(time_values, approx_interval):
    """Create bounds for mean time method.

    Parameters
    ----------
    time_values : np.ndarray
        Array of time coordinate values.
    approx_interval : float or None
        Approximate interval in days from the CMIP table.

    Returns
    -------
    np.ndarray
        Array of shape (n, 2) with start/end bounds per time point.
    """
    if len(time_values) < 2:
        raise ValueError("Cannot create mean time bounds: need at least 2 time points")

    time_diff_seconds = np.median(np.diff(time_values.astype("datetime64[s]").astype(float)))
    data_freq_days = time_diff_seconds / (24 * 3600)

    # If approx_interval matches data frequency and looks monthly, use month-aware bounds
    if approx_interval is not None and abs(data_freq_days - approx_interval) < 0.1 and 28 <= approx_interval <= 32:
        logger.info("  detected monthly data, using month-start bounds")
        return _create_monthly_bounds(time_values)

    # Default: consecutive time points as bounds
    time_diff = np.median(np.diff(time_values))
    time_values_extended = np.append(time_values, time_values[-1] + time_diff)
    return np.column_stack([time_values_extended[:-1], time_values_extended[1:]])


def _create_monthly_bounds(time_values):
    """Create monthly bounds as (month_start, next_month_start).

    Parameters
    ----------
    time_values : np.ndarray
        Array of numpy datetime64 time values.

    Returns
    -------
    np.ndarray
        Array of shape (n, 2) with monthly bounds.
    """
    import pandas as pd

    bounds_data = []
    for time_val in time_values:
        ts = pd.Timestamp(time_val)
        month_start = ts.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        if ts.month == 12:
            next_month_start = month_start.replace(year=ts.year + 1, month=1)
        else:
            next_month_start = month_start.replace(month=ts.month + 1)
        bounds_data.append([month_start.to_numpy(), next_month_start.to_numpy()])
    return np.array(bounds_data)
