"""
Set time bounds for datasets based on time method and approximate interval.

Time bounds represent the start and end of the time interval associated with
each time point. For climate data, these are required for CMIP compliance.

The main function is :func:`time_bounds` which creates appropriate bounds
based on the time method (mean, instantaneous, or climatology) and the
data's temporal frequency.
"""

import numpy as np
import xarray as xr

from ..core.logging import logger
from ..core.rule import Rule
from .dataset_helpers import get_time_label


def time_bounds(ds: xr.Dataset, rule: Rule) -> xr.Dataset:
    """
    Set time bounds for a variable based on time method and approx_interval.

    Time bounds are set according to the following logic:

    - For instantaneous time method: bounds equal the time values (delta = 0)
    - For mean time method: bounds span the averaging interval (delta > 0)
    - For climatology: no bounds are created
    - Uses approx_interval from rule to determine appropriate bounds

    Parameters
    ----------
    ds : xr.Dataset
        The input dataset.
    rule : Rule
        Rule object. Uses ``approx_interval`` (float, days) and
        ``time_method`` (str) attributes if present.

    Returns
    -------
    xr.Dataset
        The output dataset with time bounds information.

    Raises
    ------
    ValueError
        If the input is not a Dataset, has no time coordinate, or has
        insufficient time points for the requested bounds type.
    """
    dataset_name = ds.attrs.get("name", "unnamed_dataset")
    logger.info(f"[Time bounds] {dataset_name}")

    if not isinstance(ds, xr.Dataset):
        raise ValueError("The input is not a dataset.")

    time_label = get_time_label(ds)
    if time_label is None:
        raise ValueError("The dataset does not contain a valid time coordinate.")

    bounds_dim_label = "bnds"
    time_bounds_label = f"{time_label}_{bounds_dim_label}"

    approx_interval = getattr(rule, "approx_interval", None)
    time_method = getattr(rule, "time_method", None) or ds.attrs.get("time_method", "mean")

    logger.info(f"  time label: {time_label}, approx_interval: {approx_interval} days")
    logger.info(f"  time method: {time_method}")

    # Preserve existing bounds
    if time_bounds_label in ds.variables:
        logger.info(f"  using existing bounds: {time_bounds_label}")
        return ds

    if time_method not in ("mean", "instantaneous", "climatology"):
        logger.warning(f"  Unknown time method '{time_method}', defaulting to 'mean'")
        time_method = "mean"

    if time_method == "climatology":
        logger.info("  skipping bounds creation for climatology data")
        return ds

    time_var = ds[time_label]
    time_values = time_var.values

    if len(time_values) < 1:
        raise ValueError("Cannot create time bounds: no time points found")

    logger.info(f"  {len(time_values)} points from {time_values[0]} to {time_values[-1]}")

    if time_method == "instantaneous":
        bounds_data = np.column_stack([time_values, time_values])
        new_time_values = None
    else:
        bounds_data = _create_mean_bounds(time_values, approx_interval)
        # CF/CMIP and wcrp TIME001 require coord == midpoint(bnds). Source
        # files often write fixed-day-of-month timestamps (e.g. always the
        # 16th at 12:00) that are off by 1-2 days for non-31-day months.
        # Replace time with the bnds midpoint so the check passes. Skipped
        # for instantaneous time (the point IS the value).
        new_time_values = _midpoint_bounds(bounds_data)

    bounds = xr.DataArray(
        data=bounds_data,
        dims=(time_label, bounds_dim_label),
        coords={
            time_label: new_time_values if new_time_values is not None else time_values,
            # Give the bnds aux a long_name so CF §3.3 doesn't flag it
            # as a meta-data-less coord variable. Without this xarray
            # writes ``int64 bnds(bnds) ;`` with no attrs, which the
            # checker reports against every file that has time_bnds.
            bounds_dim_label: xr.DataArray(
                [0, 1], dims=(bounds_dim_label,),
                attrs={"long_name": "bounds index"},
            ),
        },
        attrs={
            "long_name": f"time bounds for {time_label}",
            "comment": f"Generated by pycmor: {time_method} time bounds",
        },
    )

    ds = ds.assign_coords({time_bounds_label: bounds})

    if new_time_values is not None:
        # Preserve attrs/encoding from the original time coord while
        # swapping in the midpoint-aligned values.
        new_time = time_var.copy(data=new_time_values)
        ds = ds.assign_coords({time_label: new_time})

    if "bounds" not in ds[time_label].attrs:
        ds[time_label].attrs["bounds"] = time_bounds_label

    # CMIP7 wcrp_cmip7 TIME003a recommends ``proleptic_gregorian`` over the
    # CF-equivalent ``standard``/``gregorian``. XIOS-produced FESOM files
    # arrive with calendar="standard"; force the encoded calendar to the
    # CMIP7-recommended form so cchecker doesn't recommend a change on
    # every file. No semantic shift — proleptic_gregorian == standard
    # for any date after 1582-10-15, and our experiments start in 1850.
    cal_enc = ds[time_label].encoding.get("calendar")
    cal_attr = ds[time_label].attrs.get("calendar")
    if (cal_enc in (None, "standard", "gregorian")) and (cal_attr in (None, "standard", "gregorian")):
        ds[time_label].encoding["calendar"] = "proleptic_gregorian"
        # Keep the attr out — encoding wins at write time, and a stale
        # attr would confuse downstream readers.
        ds[time_label].attrs.pop("calendar", None)

    logger.info(f"  set {time_bounds_label}{bounds.shape}, " f"range: {bounds.values[0][0]} to {bounds.values[-1][-1]}")
    return ds


def _midpoint_bounds(bounds_data):
    """Per-row midpoint of a (n, 2) time-bounds array.

    Handles both numpy ``datetime64`` and ``cftime`` object arrays. The
    midpoint is computed as ``b0 + (b1 - b0) / 2`` rather than
    ``np.mean(axis=1)`` so that cftime calendars (proleptic_gregorian,
    noleap, 360_day, ...) round-trip correctly — ``np.mean`` doesn't
    know how to average cftime objects.
    """
    if np.issubdtype(bounds_data.dtype, np.datetime64):
        return bounds_data[:, 0] + (bounds_data[:, 1] - bounds_data[:, 0]) / 2
    return np.array(
        [b0 + (b1 - b0) / 2 for b0, b1 in bounds_data],
        dtype=object,
    )


def _create_mean_bounds(time_values, approx_interval):
    """Create bounds for mean time method.

    Parameters
    ----------
    time_values : np.ndarray
        Array of time coordinate values.
    approx_interval : float or None
        Approximate interval in days from the CMIP table.

    Returns
    -------
    np.ndarray
        Array of shape (n, 2) with start/end bounds per time point.
    """
    if len(time_values) < 2:
        raise ValueError("Cannot create mean time bounds: need at least 2 time points")

    time_diff_seconds = np.median(np.diff(time_values.astype("datetime64[s]").astype(float)))
    data_freq_days = time_diff_seconds / (24 * 3600)

    # Use month-aware bounds when the data spacing IS monthly. approx_interval
    # is an optional sanity check; if set, it must also indicate monthly,
    # otherwise we fall through to consecutive-step bounds. The previous
    # logic required approx_interval to be set, which silently degraded
    # broadcast-style pipelines (cfc11, ch4, ...) where the rule doesn't
    # carry a DReq-derived interval.
    data_looks_monthly = 27 <= data_freq_days <= 32
    approx_disagrees = approx_interval is not None and not (28 <= approx_interval <= 32)
    if data_looks_monthly and not approx_disagrees:
        logger.info("  detected monthly data, using month-start bounds")
        return _create_monthly_bounds(time_values)

    # Default: consecutive time points as bounds
    time_diff = np.median(np.diff(time_values))
    time_values_extended = np.append(time_values, time_values[-1] + time_diff)
    return np.column_stack([time_values_extended[:-1], time_values_extended[1:]])


def _create_monthly_bounds(time_values):
    """Create monthly bounds as (month_start, next_month_start).

    Parameters
    ----------
    time_values : np.ndarray
        Array of numpy datetime64 time values.

    Returns
    -------
    np.ndarray
        Array of shape (n, 2) with monthly bounds.
    """
    import pandas as pd

    bounds_data = []
    for time_val in time_values:
        ts = pd.Timestamp(time_val)
        month_start = ts.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        if ts.month == 12:
            next_month_start = month_start.replace(year=ts.year + 1, month=1)
        else:
            next_month_start = month_start.replace(month=ts.month + 1)
        bounds_data.append([month_start.to_numpy(), next_month_start.to_numpy()])
    return np.array(bounds_data)
